on: [push, pull_request]
name: CI

jobs:
  build:
    strategy:
      matrix:
        name: [gcc, clang]
        include:
          - name: gcc
            env:
              CC: gcc
              CXX: g++
          - name: clang
            env:
              CC: clang
              CXX: clang++

    name: ${{ matrix.name }}
    runs-on: [ubuntu-latest]

    steps:

    - uses: actions/checkout@v2

    - name: Environment
      run: |
        echo "::set-env name=CC::${{ matrix.env.CC }}"
        echo "::set-env name=CXX::${{ matrix.env.CXX }}"

    - name: Packages
      run: |
        sudo mkdir -p /usr/share/man/man1
        sudo apt-get update
        sudo apt-get install -y \
          bison \
          build-essential \
          clang \
          cmake \
          flex \
          gcc \
          git \
          ninja-build \
          python3 \
          python3-pip \
          python3-setuptools \
          zlib1g-dev
        sudo pip3 install -U lit

    - name: Dependencies
      run: |
        ./contrib/setup-minisat.sh
        ./contrib/setup-cms.sh
        ./contrib/setup-gtest.sh
        ./contrib/setup-outputcheck.sh

    - name: Configure
      run: |
        mkdir build
        cd build
        cmake -DNOCRYPTOMINISAT:BOOL=OFF -DENABLE_TESTING:BOOL=ON -DPYTHON_EXECUTABLE:PATH=$(which python3) -G Ninja ..

    - name: Build
      run: ninja -j8
      working-directory: build

    - name: Test
      run: ctest -j8
      working-directory: build

## EOF
